### ISSUE TITLE
Error after initial installation/activation

### ISSUE THREAD

**Issue by Bukunmikuti** [bibleup/wordpress#3]
The below error displays on screen but plugin still gets activated.
Warning: Undefined array key "subtitle" in C:\xampp\htdocs\bibleup\wp-content\plugins\bibleup\wp-settings-framework\wp-settings-framework.php on line 349

**Comment by corrosive4354** [comment]
you can use [Servbay](servbay.com) instead of Xampp to deploy. Servbay can install the packages you need and eliminate environment bugs

**Comment by Bukunmikuti** [comment]
closed by #5
